[package]
name = "blanc-rs"
version = "0.1.0-alpha"
edition = "2018"

[dependencies]
rustyline = "9.0.0"

[lib]
name = "blanc"
path = "src/lib.rs"
doctest = false

[[bin]]
name = "repl"
path = "repl/main.rs"
