[package]
name = "blanc-rs"
version = "0.1.0-pre-alpha"
edition = "2018"

[dependencies]
colored = "2.0.0"
clap = "2.33.0"
rustyline = "9.0.0"

[lib]
name = "blanc"
path = "src/lib.rs"
doctest = false

[[bin]]
name = "blanci"
path = "cli/main.rs"
test = false
